### ISSUE TITLE
NoneType object has no attribute 'url'

### ISSUE THREAD

**Issue by moritzj29** [avanc/photOS-matrix#1]
Hello,

I was just trying to set up this project as I would like to use the matrix chat option for photOS. I set up Raspi and all the configs and I can issue the `!help` command and get replies. But I'm not able to receive images...

When I send an image, the `matrix.log` says:
```
[2022-03-09 12:25:37,025] [ERROR@__main__] 'NoneType' object has no attribute 'url'
```
I already set the log levels in the `matrix-config.yml`to `DEBUG` but this is the only message shown.

I have not much experience with matrix yet, I just setup synapse for this project. But since the text commands work and images are displayed when I log into the account on a different device, I assume it is related to the photOS implementation.

Any help on tracking this down is very much appreciated!

**Comment by avanc** [comment]
Hopefully, @universalappfactory can help here?

**Comment by universalappfactory** [comment]
Hi,
do you have encryption enabled for this room?
At first glance the error comes from:

photos_client.py:
`encrypted_data = await self.client.download_media(media_content.file.url)`

and this is only set when it's an encrypted message.

Otherwise I have to investigate a bit more.

I also hope to push an update soon when I have some more time as there is a problem with the initial sync when the device was turned off.

**Comment by moritzj29** [comment]
Hi, thanks for your fast reaction!

The hint on encryption was helpful. According to the Element App encryption was not enabled for the room. I enabled it and now the images are received and I get reply messages!

There is no possibility to remove images, correct? Like "only keep images of the last 6 months".

Thank you very much for your help!

**Comment by universalappfactory** [comment]
Ok cool, I've added a proper error message for the next version.

> `There is no possibility to remove images, correct? Like "only keep images of the last 6 months".`
Yes correct, the only thing you can set at the moment is min_free_disk_space_mb

**Comment by moritzj29** [comment]
thanks! Maybe I will combine the WebDAV and the Matrix approach. Use the more stable/tested WebDAV image for the pi and host your matrix package inside a docker container to receive the images and serve them via WebDAV. In this way I would have full control over the served images… 
I will set up the pi in a remote location so I need it to be very stable and without needs to update.
Anyway, I think your code will be a very great help! I have not found any „chat bot“ to just listen and store images yet.
If you are interested, I can share my approach ~~here~~ in `matrix-photos`repo, once it is working.
